#!/usr/bin/env python3
"""Convert binary table_s* files from java-airplay JAR into Rust const arrays.

Usage:
    python convert_tables.py [tables_dir]
    
Output: rust_tables.rs (Rust source with all const arrays)
"""
import sys, os, struct

TABLES_DIR = sys.argv[1] if len(sys.argv) > 1 else "."

def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()

def read_ints_from_text(path):
    """table_s5..s9 are text files with one decimal integer per line."""
    ints = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                # Handle hex (0x...) and signed decimal
                val = int(line, 0)
                # Convert signed 32-bit to unsigned representation
                if val < 0:
                    val = val & 0xFFFFFFFF
                ints.append(val)
    return ints

def format_byte_array(name, data):
    lines = []
    lines.append(f"pub const {name}: [u8; {len(data)}] = [")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        formatted = ", ".join(str(b) for b in chunk)
        if i + 16 < len(data):
            lines.append(f"    {formatted},")
        else:
            lines.append(f"    {formatted}")
    lines.append("];")
    return "\n".join(lines)

def format_u32_array(name, data):
    lines = []
    lines.append(f"pub const {name}: [u32; {len(data)}] = [")
    for i in range(0, len(data), 8):
        chunk = data[i:i+8]
        formatted = ", ".join(f"0x{v:08X}" for v in chunk)
        if i + 8 < len(data):
            lines.append(f"    {formatted},")
        else:
            lines.append(f"    {formatted}")
    lines.append("];")
    return "\n".join(lines)

def main():
    # Byte tables
    byte_tables = ["TABLE_S1", "TABLE_S2", "TABLE_S3", "TABLE_S4", "TABLE_S10"]
    file_map = {
        "TABLE_S1": "table_s1",
        "TABLE_S2": "table_s2",
        "TABLE_S3": "table_s3",
        "TABLE_S4": "table_s4",
        "TABLE_S10": "table_s10",
        "TABLE_S5": "table_s5",
        "TABLE_S6": "table_s6",
        "TABLE_S7": "table_s7",
        "TABLE_S8": "table_s8",
        "TABLE_S9": "table_s9",
    }

    out_lines = [
        "//! Auto-generated lookup tables from java-airplay JAR resources.",
        "//! Generated by: python convert_tables.py",
        "//! Source: java-airplay v1.0.7, BOOT-INF/lib/lib-1.0.6.jar",
        "",
    ]

    for rust_name in ["TABLE_S1", "TABLE_S2", "TABLE_S3", "TABLE_S4", "TABLE_S10"]:
        fname = file_map[rust_name]
        path = os.path.join(TABLES_DIR, fname)
        data = read_bytes(path)
        out_lines.append(format_byte_array(rust_name, data))
        out_lines.append("")

    for rust_name in ["TABLE_S5", "TABLE_S6", "TABLE_S7", "TABLE_S8", "TABLE_S9"]:
        fname = file_map[rust_name]
        path = os.path.join(TABLES_DIR, fname)
        data = read_ints_from_text(path)
        out_lines.append(format_u32_array(rust_name, data))
        out_lines.append("")

    output = "\n".join(out_lines)
    
    # Write to file
    out_path = os.path.join(TABLES_DIR, "rust_tables.rs")
    with open(out_path, "w") as f:
        f.write(output)
    
    print(f"Generated {out_path}")
    
    # Print stats
    for rust_name, fname in file_map.items():
        path = os.path.join(TABLES_DIR, fname)
        size = os.path.getsize(path)
        print(f"  {rust_name}: {size:,} bytes")

if __name__ == "__main__":
    main()
